# Shim de rétrocompatibilité — redirige vers le sous-module text_tools/
# Tous les imports `from .text_tools_service import X` continuent de fonctionner.
from .text_tools import (  # noqa: F401
    reformulate,
    translate,
    correct,
    generate_email,
    expand_text,
    extract_data,
    simplify_text,
    compare_decide,
    explain_eli5,
    generate_summary,
    convert_format,
    generate_script,
    generate_mermaid,
    generate_regex,
    generate_prompt,
    generate_documentation,
    generate_todolist,
    generate_flashcards,
    generate_recipe,
    generate_fitness,
    generate_admin_letter,
    generate_speech,
    get_history,
    get_history_item,
    clear_history,
    delete_history_item,
)
