services:
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    #ports:
    #  - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng
    restart: always
    networks:
      - nova

